name: Broken Links

on:
  workflow_dispatch:

jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://qiskit.org
          cmd_params: "--buffer-size=8192 --max-connections=10 --color=always --skip-tls-verification --exclude=\"(https://qiskit.org/documentation|https://qiskit.org/ecosystem/.*|https://medium.com/Qiskit|https://qiskit.org/cdn-cgi/l/email-protection)\" --timeout=60"
