name: Preview (clean)

on:
  pull_request:
    types: [closed]

jobs:
  teardown:
    # This job requires secrets, which cannot be accessed by forks or dependabot
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot' }}

    uses: Qiskit/gh-actions/.github/workflows/code-engine-cleanup.yml@main
    with:
      code_engine_project: qiskit.org-preview
      docker_image_name: qiskit-org
    secrets:
      ibmcloud_account: ${{ secrets.IBMCLOUD_ACCOUNT }}
      ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
